spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_apply?serverTimezone=GMT%2B8&useUnicode=true&characterEncodeing=UTF-8&useSSL=false
    username: root
    password: root
#  redis:
#    host: 82.157.42.25
#    port: 6379
#    password: Redis123
#    database: 1
#  rabbitmq:
#    host: 82.157.42.25
#    port: 5672
#    username: guest
#    password: guest
server:
  port: 8088
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
# JWT令牌密钥
application:
  security:
    secret: salt
# 枚举类包路径
  enum:
    default:
      package:
        path: org.example.common.enums.impl
# 支付宝支付ID、私钥、公钥
#alipay:
#  info:
#    appId:
#    privateKey:
#    alipayPublicKey:
# Email邮箱配置信息: 账号、授权码
email:
  emailAccount:
  authCode: